### ISSUE TITLE
Checkboxes treat `0` as checked

### ISSUE THREAD

**Issue by alanhogan** [zeelot/kohana-yform#19]
(value-less, in particular) checkboxes should treat false and zero as un-checked.

**Comment by zeelot** [comment]
closed by 392253cec1dbe325cf46ac5c17c89718b8396e9a now checking the box if $value is any non-false value... this _should_ be fine

**Comment by zeelot** [comment]
I expected the value to simply not be there, but obviously if the value comes from a database and is FALSE or 0, it should still be unchecked...
