### ISSUE TITLE
Formatting of required fields

### ISSUE THREAD

**Issue by dtb** [zeelot/kohana-yform#20]
When doing ->set('required', TRUE), there's a space between the label and the *, which looks horrible. We also tried manually specifying a '*' for the second parameter, but the space was still there!!

**Comment by zeelot** [comment]
alright, will take care of this during lunch or tonight

**Comment by zeelot** [comment]
sorry about the delay, doing this definitely doing lunch today

**Comment by zeelot** [comment]
removing whitespace in labels and legends, closed by d82f520135ea4b473ba23776f1c60f34be3f1326
