### ISSUE TITLE
Error display for RadioGroup and CheckboxGroup

### ISSUE THREAD

**Issue by dtb** [zeelot/kohana-yform#21]
Radio and checkbox groups display errors after each individual element. They should be fixed to only display the error at the end of the group. There _might_ be a use case where someone also wants to display an error near a specific option, but I'm not really sure. I would expect the default/easier way of specifying errors to put them after the group.

I fixed this in nestablish by overriding RadioGroup and CheckboxGroup to clear out the `_messages['errors']` array element on the options it creates. See [29dae8bL16](https://github.com/synapsestudios/nestablish.com/commit/291dae8b23fe5f4bdbfeb495732c0b8e7ee6399a#L0R16). This is likely not a good fix, but I didn't see any official way to remove or modify the errors or messages.

**Comment by zeelot** [comment]
the solution would be for any radio or checkbox created by the group classes to 'find' messages in name.value instead of just name like all other elements... does that sound right to you? because a radiogroup of colors should put the error located at $errors[colors][red] under the red radio option (where the value is red)

let me know if that sounds logical to you guys

**Comment by zeelot** [comment]
also, how are you setting _messages? it's protected

**Comment by dtb** [comment]
That sounds right to me.

Protected and private properties may be accessed by _instances of the same class_. It is a common mistake that people think that it must be the _same instance of the class_. See [here](http://stackoverflow.com/questions/888224/long-held-incorrect-programming-assumptions/888246#888246).

**Comment by zeelot** [comment]
quite interesting... not sure why I never questioned that part of my horrible college education

**Comment by zeelot** [comment]
this seems to only be an issue on radioGroup, not checkboxGroup

**Comment by zeelot** [comment]
changing the path that radio buttons use, closed by b401f69c80cf6b24f15fe6b9e0715cbf87c2fae3
