### ISSUE TITLE
Improper naming for groups when field has hard brackets

### ISSUE THREAD

**Issue by alanhogan** [zeelot/kohana-yform#24]
```
$yf = YForm::factory();
//...
$ylic = $yf->group('license');
echo $ylic->select('state_id[]');
```

This will output a field named `license[state_id[]]` when it should be called `license[state_id][]`.

**Comment by zeelot** [comment]
can't reproduce

**Comment by alanhogan** [comment]
I think you tried this, but it was a group like `foo` and then a select() or text() named `bar[]`
