### ISSUE TITLE
YForm::factory() results in invalid HTML

### ISSUE THREAD

**Issue by alanhogan** [zeelot/kohana-yform#25]
If `YForm::factory()` is called without its argument (a string to be used for the ID of the form), which I don’t believe to be necessary, then
1. No error results / no exception is thrown and the method succeeds, but
2. Rendering the form will include the string `id=""`. This is invalid HTML:
   
   >  Line 37, Column 89: Bad value for attribute id on element form: An ID must not be the empty string.

**Comment by zeelot** [comment]
not adding blank IDs, closed by e22214e75f80f8e43cb030eab989e4427b658a4d
