### ISSUE TITLE
fatal error when running unit tests

### ISSUE THREAD

**Issue by bobeagan** [zeelot/kohana-yform#41]
PHP Fatal error:  Class 'Controller_Yuriko_Template' not found in /var/lib/hudson/jobs/Kohana-Project-Template-0.7.x/workspace/modules/yform/classes/controller/yform/demo.php on line 10

**Comment by zeelot** [comment]
removing the demo controller (will need to add kohana docs) (closed by 8c1b2b8cec297fd5fbae97f8051f110262162f90)
