### ISSUE TITLE
Remove unused file from dev/1.0.x branch

### ISSUE THREAD

**Issue by bobeagan** [zeelot/kohana-yform#45]
PHP Fatal error:  Class 'Yuriko_YForm_Message' not found in /var/lib/hudson/jobs/synapsestudios.com-develop/workspace/modules/yform/classes/yform/message.php on line 10

You did this already for the dev/1.1.x branch (e95913ecc5a53fc6ce2814de09a21b6fc9b236d6)

**Comment by zeelot** [comment]
removing an unused class (closed by 08811c8a044eea89f4d29033adc8f8b49825bf86)
